index:
    path: /
    controller: App\Controller\UserController::index
    methods: GET

signin:
    path: /signin
    controller: App\Controller\SecurityController::login
    methods: POST
    
signup:
    path: /signup
    controller: App\Controller\UserController::signUp

register_user:
    path: /register
    controller: App\Controller\UserController::registerUser
    methods: POST

view_user:
    path: /view_user/{id}
    controller: App\Controller\UserController::viewUser
    methods: GET

delete_user:
    path: /delete_user/{id}
    controller: App\Controller\UserController::deleteUser
    methods: GET

view_all_users:
    path: /view_all_users
    controller: App\Controller\UserController::view_all_users
    methods: GET

login:
    path: /login
    controller: App\Controller\UserController::userAuthenticate
    methods: POST

logOut:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: GET